---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: blazar
  namespace: openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  mariaDbRef:
    name: mariadb-cluster
  characterSet: utf8
  collate: utf8_general_ci
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: blazar
  namespace: openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  mariaDbRef:
    name: mariadb-cluster
  passwordSecretKeyRef:
    name: blazar-secrets
    key: db-password
  maxUserConnections: 0
  host: "%"
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: blazar-grant
  namespace: openstack
  annotations:
    helm.sh/resource-policy: keep
spec:
  mariaDbRef:
    name: mariadb-cluster
  privileges:
    - "ALL"
  database: "blazar"
  table: "*"
  username: blazar
  grantOption: true
  host: "%"
  retryInterval: 5s
