bases:
  - ../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: blazar-api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
