_region: &region DFW3
images:
  tags:
    bootstrap: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    db_init: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    db_drop: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    ks_user: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    ks_service: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    ks_endpoints: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    glance_db_sync: "docker.io/openstackhelm/glance:2023.1-ubuntu_jammy"
    glance_api: "docker.io/openstackhelm/glance:2023.1-ubuntu_jammy"
    glance_metadefs_load: "docker.io/openstackhelm/glance:2023.1-ubuntu_jammy"
    glance_storage_init: "docker.io/openstackhelm/ceph-config-helper:ubuntu_focal_18.2.0-1-20231013"
    entrypoint: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    ingress: registry.k8s.io/ingress-nginx/controller:v1.8.2
    ingress_module_init: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    ingress_routed_vip: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    error_pages: registry.k8s.io/defaultbackend:1.4
    keepalived: docker.io/osixia/keepalived:1.4.5
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    image_repo_sync: docker.io/library/docker:17.07.0
    heat_db_sync: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    heat_api: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    heat_cfn: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    heat_cloudwatch: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    heat_engine: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    heat_engine_cleaner: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    heat_purge_deleted: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    test: docker.io/xrally/xrally-openstack:2.0.0
    rabbit_init: docker.io/rabbitmq:3.7-management
    cinder_db_sync: "docker.io/openstackhelm/cinder:2023.1-ubuntu_jammy"
    cinder_api: "docker.io/openstackhelm/cinder:2023.1-ubuntu_jammy"
    cinder_scheduler: "docker.io/openstackhelm/cinder:2023.1-ubuntu_jammy"
    cinder_volume: "docker.io/openstackhelm/cinder:2023.1-ubuntu_jammy"
    cinder_volume_usage_audit: "docker.io/openstackhelm/cinder:2023.1-ubuntu_jammy"
    cinder_storage_init: "docker.io/openstackhelm/ceph-config-helper:ubuntu_focal_18.2.0-1-20231013"
    cinder_backup: "docker.io/openstackhelm/cinder:2023.1-ubuntu_jammy"
    cinder_backup_storage_init: "docker.io/openstackhelm/ceph-config-helper:ubuntu_focal_18.2.0-1-20231013"
    keystone_api: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_bootstrap: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    keystone_credential_rotate: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_credential_setup: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_db_sync: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_domain_manage: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_fernet_rotate: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_fernet_setup: "ghcr.io/rackerlabs/genestack/keystone-rxt:2023.1-ubuntu_jammy"
    keystone_credential_cleanup: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    libvirt: docker.io/openstackhelm/libvirt:2023.2-ubuntu_jammy  # We want to use jammy. 2023.2 is the latest version that supports jammy.
    libvirt_exporter: vexxhost/libvirtd-exporter:latest
    ceph_config_helper: "docker.io/openstackhelm/ceph-config-helper:ubuntu_focal_18.2.0-1-20231013"
    kubectl: docker.io/bitnami/kubectl:latest
    neutron_db_sync: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_dhcp: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_l3: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_l2gw: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_linuxbridge_agent: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_metadata: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_ovn_metadata: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_openvswitch_agent: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_server: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_rpc_server: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_bagpipe_bgp: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_netns_cleanup_cron: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    purge_test: docker.io/openstackhelm/ospurge:latest
    netoffload: ghcr.io/vexxhost/netoffload:v1.0.1
    neutron_sriov_agent: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_sriov_agent_init: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_bgp_dragent: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    neutron_ironic_agent: "docker.io/openstackhelm/neutron:2023.1-ubuntu_jammy"
    nova_api: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_cell_setup: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_cell_setup_init: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    nova_compute: "ghcr.io/rackerlabs/genestack/nova-efi:2023.1-ubuntu_jammy"
    nova_compute_ssh: "ghcr.io/rackerlabs/genestack/nova-efi:2023.1-ubuntu_jammy"
    nova_conductor: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_db_sync: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_novncproxy: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_novncproxy_assets: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_scheduler: "ghcr.io/rackerlabs/genestack/nova-efi:2023.1-ubuntu_jammy"
    nova_spiceproxy: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_spiceproxy_assets: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_service_cleaner: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_focal"
    nova_archive_deleted_rows: "docker.io/openstackhelm/nova:2023.1-ubuntu_jammy"
    nova_compute_ironic: "docker.io/kolla/nova-compute-ironic:2023.2-ubuntu-jammy"
    nova_wait_for_computes_init: gcr.io/google_containers/hyperkube-amd64:v1.11.6
    placement: "docker.io/openstackhelm/placement:2023.1-ubuntu_jammy"
    placement_db_sync: "docker.io/openstackhelm/placement:2023.1-ubuntu_jammy"
    horizon_db_sync: docker.io/openstackhelm/horizon:2023.1-ubuntu_jammy
    horizon: docker.io/openstackhelm/horizon:2023.1-ubuntu_jammy
    octavia_db_sync: ghcr.io/rackerlabs/genestack/octavia-ovn:master-ubuntu_jammy
    octavia_api: ghcr.io/rackerlabs/genestack/octavia-ovn:master-ubuntu_jammy
    octavia_worker: ghcr.io/rackerlabs/genestack/octavia-ovn:master-ubuntu_jammy
    octavia_housekeeping: ghcr.io/rackerlabs/genestack/octavia-ovn:master-ubuntu_jammy
    octavia_health_manager: ghcr.io/rackerlabs/genestack/octavia-ovn:master-ubuntu_jammy
    octavia_health_manager_init: "docker.io/openstackhelm/heat:2023.1-ubuntu_jammy"
    openvswitch_vswitchd: docker.io/kolla/centos-source-openvswitch-vswitchd:rocky

pod:
  resources:
    enabled: false

endpoints:
  compute:
    host_fqdn_override:
      public:
        tls: {}
        host: nova.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  compute_metadata:
    host_fqdn_override:
      public:
        tls: {}
        host: metadata.nova.dfw-ospcv2-staging.ohthree.com
    port:
      metadata:
        public: 443
    scheme:
      public: https
  compute_novnc_proxy:
    host_fqdn_override:
      public:
        tls: {}
        host: novnc.nova.dfw-ospcv2-staging.ohthree.com
    port:
      novnc_proxy:
        public: 443
    scheme:
      public: https
  cloudformation:
    host_fqdn_override:
      public:
        tls: {}
        host: cloudformation.heat.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  cloudwatch:
    host_fqdn_override:
      public:
        tls: {}
        host: cloudwatch.heat.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  dashboard:
    host_fqdn_override:
      public:
        tls: {}
        host: dfw-ospcv2-staging.ohthree.com
    port:
      web:
        public: 443
    scheme:
      public: https
  identity:
    auth:
      admin:
        region_name: *region
      cinder:
        region_name: *region
      designate:
        region_name: *region
      glance:
        region_name: *region
      heat:
        region_name: *region
      heat_trustee:
        region_name: *region
      heat_stack_user:
        region_name: *region
      ironic:
        region_name: *region
      neutron:
        region_name: *region
      nova:
        region_name: *region
      placement:
        region_name: *region
    host_fqdn_override:
      public:
        tls: {}
        host: keystone.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  ingress:
    port:
      ingress:
        public: 443
  image:
    host_fqdn_override:
      public:
        tls: {}
        host: glance.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  load_balancer:
    host_fqdn_override:
      public:
        tls: {}
        host: octavia.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  network:
    host_fqdn_override:
      public:
        tls: {}
        host: neutron.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  orchestration:
    host_fqdn_override:
      public:
        tls: {}
        host: heat.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  placement:
    host_fqdn_override:
      public:
        tls: {}
        host: placement.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  volume:
    host_fqdn_override:
      public:
        tls: {}
        host: cinder.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  volumev2:
    host_fqdn_override:
      public:
        tls: {}
        host: cinder.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https
  volumev3:
    host_fqdn_override:
      public:
        tls: {}
        host: cinder.dfw-ospcv2-staging.ohthree.com
    port:
      api:
        public: 443
    scheme:
      public: https

manifests:
  secret_ingress_tls: true

bootstrap:
  structured:
    images: {}

network:
  api:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"

volume:
  class_name: general-multi-attach
  size: 100Gi
